config/routes.rb
Rails.application.routes.draw do
  resources :answers
  root to: "questions#index"
  resources :questions
end

app/models/answer.rb
class Answer < ApplicationRecord

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :title, :content, :tags, :presence => true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def index
    @answers = Answer.all
  end

  def show
    @answer = Answer.find(params[:id])
  end

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
    flash[:notice] = "Answer successfully added!"
      redirect_to  answers_path
    else
      render :new
    end
  end

  def edit
    @answer = Answer.find(params[:id])
  end

  def update
    @answer= Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:notice] = "Answer successfully updated!"
      redirect_to answers_path
    else
      render :edit
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    if @answer.destroy
      flash[:notice] = "Answer successfully removed!"
      redirect_to answers_path
    end
  end

private
  def answer_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:answer).permit(:attribute1, :attribute2, :attribute3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
    flash[:notice] = "Question successfully added!"
      redirect_to  questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question= Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Question successfully updated!"
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    if @question.destroy
      flash[:notice] = "Question successfully removed!"
      redirect_to questions_path
    end
  end

private
  def question_params
    # Use strict parameters, replace placeholder info below with your class' actual attributes
    params.require(:question).permit(:title, :content, :tags)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render "layouts/errors", :object => @answer %>

<%= form_for @answer do |f| %>
  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<h1>Edit Answer</h1>

<%= render "form" %>

app/views/answers/index.html.erb
<h1>Answers</h1>

<ul>
  <% @answers.each do |answer| %>
    <li><%= link_to "Show", answer_path(answer) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Answer", new_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render "form" %>

app/views/answers/show.html.erb
<h1>Show Answer</h1>

<p><%= link_to "Edit", edit_answer_path(@answer) %></p>
<p><%= link_to "Delete", answer_path(@answer),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to answers", answers_path %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stackoverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span id="image" href="#"><%= image_tag "stack.png"%></span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "StackOverFlow", root_path %></li>
        <li id ="question"><%= link_to 'Questions', root_path %></li>
        <li id ="question"><%= link_to 'Add questions', new_question_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for @question do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br>
<%= f.label :content %>
<%= f.text_field :content %>
<br>
<%= f.label :tags %>
<%= f.text_field :tags %>
<br>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %></li>
  <% end %>
</ul>

<hr>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1>Show Question</h1>

<div class="row">
  <div class="col-md-6">
    <h1><%= @question.title %></h1>
    <h2><%= @question.content %>$</h2>
    <h3><%= @question.tags%></h3>
  </div>


<p><%= link_to "Edit", edit_question_path(@question) %></p>
<p><%= link_to "Delete", question_path(@question),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>
<p><%= link_to "Return to questions", questions_path %></p>